import { Timestamp } from "firebase-admin/firestore";
import type { Response } from "express";
import type { AuthenticatedRequest } from "../../middlewares/auth.middleware";
import { db } from "../../config/firebase";
import { getCurrentPrivacyPolicy } from "./privacy-policy.service";

const serialize = (doc: FirebaseFirestore.DocumentSnapshot) => { const data: any = doc.data() ?? {}; const date = (value: any) => value?.toDate?.()?.toISOString?.() ?? null; return { id: doc.id, ...data, createdAt: date(data.createdAt), publishedAt: date(data.publishedAt) }; };
export const listPolicies = async (_req: AuthenticatedRequest, res: Response) => { const snapshot = await db.collection("privacy_policies").get(); const items = snapshot.docs.map(serialize).sort((a: any, b: any) => String(b.createdAt).localeCompare(String(a.createdAt))); res.json({ current: await getCurrentPrivacyPolicy(), items }); };
export const createPolicy = async (req: AuthenticatedRequest, res: Response) => { const { version, title, summary, termsContent, privacyContent, publish } = req.body ?? {}; if (![version, title, termsContent, privacyContent].every((value) => String(value ?? "").trim())) return res.status(400).json({ message: "Versão, título, termos e política são obrigatórios." }); const duplicate = await db.collection("privacy_policies").where("version", "==", String(version).trim()).get(); if (!duplicate.empty) return res.status(409).json({ message: "Já existe uma política com esta versão." }); const ref = db.collection("privacy_policies").doc(); const now = Timestamp.now(); const shouldPublish = publish === true; await db.runTransaction(async (transaction) => { if (shouldPublish) { const published = await transaction.get(db.collection("privacy_policies").where("status", "==", "published")); published.docs.forEach((doc) => transaction.update(doc.ref, { status: "archived", updatedAt: now })); } transaction.set(ref, { version: String(version).trim(), title: String(title).trim(), summary: String(summary ?? "").trim(), termsContent: String(termsContent).trim(), privacyContent: String(privacyContent).trim(), status: shouldPublish ? "published" : "draft", createdAt: now, updatedAt: now, publishedAt: shouldPublish ? now : null, createdBy: req.user!.uid }); }); return res.status(201).json({ id: ref.id, message: shouldPublish ? "Política publicada." : "Rascunho salvo." }); };
export const publishPolicy = async (req: AuthenticatedRequest, res: Response) => { const ref = db.collection("privacy_policies").doc(req.params.id); const target = await ref.get(); if (!target.exists) return res.status(404).json({ message: "Política não encontrada." }); const now = Timestamp.now(); await db.runTransaction(async (transaction) => { const published = await transaction.get(db.collection("privacy_policies").where("status", "==", "published")); published.docs.forEach((doc) => transaction.update(doc.ref, { status: "archived", updatedAt: now })); transaction.update(ref, { status: "published", publishedAt: now, updatedAt: now, publishedBy: req.user!.uid }); }); return res.json({ message: "Nova versão publicada. Os usuários deverão aceitá-la no próximo acesso." }); };

export const listDeletionRequests = async (_req: AuthenticatedRequest, res: Response) => { const snapshot = await db.collection("account_deletion_requests").get(); const date = (value: any) => value?.toDate?.()?.toISOString?.() ?? null; const items = await Promise.all(snapshot.docs.map(async (doc) => { const data: any = doc.data(); let userName = data.userName; let userEmail = data.userEmail; if (!userName || !userEmail) { const user = await db.collection("users").doc(data.userId ?? doc.id).get(); userName ||= user.data()?.name; userEmail ||= user.data()?.email; } return { id: doc.id, ...data, userName: userName ?? "Usuário", userEmail: userEmail ?? "", requestedAt: date(data.requestedAt), scheduledDeletionAt: date(data.scheduledDeletionAt), cancelledAt: date(data.cancelledAt) }; })); items.sort((a, b) => String(b.requestedAt).localeCompare(String(a.requestedAt))); return res.json(items); };

export const cancelDeletionRequestAdmin = async (req: AuthenticatedRequest, res: Response) => { const ref = db.collection("account_deletion_requests").doc(req.params.id); const snapshot = await ref.get(); if (!snapshot.exists) return res.status(404).json({ message: "Solicitação não encontrada." }); const now = Timestamp.now(); const batch = db.batch(); batch.set(ref, { status: "cancelled_by_admin", cancelledAt: now, cancelledBy: req.user!.uid }, { merge: true }); const supportId = snapshot.data()?.supportId; if (supportId) batch.set(db.collection("supports").doc(supportId), { status: "fechado", closedAt: now, updatedAt: now }, { merge: true }); await batch.commit(); return res.json({ message: "Solicitação cancelada pela administração." }); };
