import { Timestamp } from "firebase-admin/firestore";
import type { Response } from "express";
import type { AuthenticatedRequest } from "../../middlewares/auth.middleware";
import { auth, db } from "../../config/firebase";
import { getCurrentPrivacyPolicy } from "./privacy-policy.service";
import { userGamificationRef } from "../gamification/user-gamification.repository";

const USER_COLLECTIONS = ["enrollments", "certificates", "supports", "experience_feedback", "game_sessions", "assessment_attempts", "sketchbook_tabs", "timeline", "user_sessions"];
const docs = (snapshot: FirebaseFirestore.QuerySnapshot) => snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }));

export const getCurrentPolicy = async (_req: AuthenticatedRequest, res: Response) => res.json(await getCurrentPrivacyPolicy());
export const getPrivacyStatus = async (req: AuthenticatedRequest, res: Response) => { const [policy, consent, deletion, sessions] = await Promise.all([getCurrentPrivacyPolicy(), db.collection("privacy_consents").doc(req.user!.uid).get(), db.collection("account_deletion_requests").doc(req.user!.uid).get(), db.collection("user_sessions").where("userId", "==", req.user!.uid).get()]); res.json({ policyVersion: policy.version, policy, requiresAcceptance: consent.data()?.policyVersion !== policy.version, consent: consent.exists ? consent.data() : null, deletionRequest: deletion.exists ? deletion.data() : null, sessions: docs(sessions).map((item: any) => ({ ...item, lastSeenAt: item.lastSeenAt?.toDate?.()?.toISOString?.() ?? null })), retention: { auditLogsDays: 1825, operationalLogsDays: 180, inactiveSessionsDays: 180, deletionGraceDays: 30 } }); };
export const acceptPrivacy = async (req: AuthenticatedRequest, res: Response) => { const accepted = req.body?.accepted === true; if (!accepted) return res.status(400).json({ message: "É necessário confirmar o consentimento." }); const policy = await getCurrentPrivacyPolicy(); if (req.body?.policyVersion && req.body.policyVersion !== policy.version) return res.status(409).json({ message: "A política foi atualizada. Recarregue para ler a versão atual." }); const data = { userId: req.user!.uid, policyVersion: policy.version, accepted: true, acceptedAt: Timestamp.now(), ip: req.ip, userAgent: req.get("user-agent") }; await db.collection("privacy_consents").doc(req.user!.uid).set(data); return res.json({ message: "Consentimento registrado.", ...data }); };
export const exportMyData = async (req: AuthenticatedRequest, res: Response) => { const uid = req.user!.uid; const policy = await getCurrentPrivacyPolicy(); const [user, gamification, ...snapshots] = await Promise.all([db.collection("users").doc(uid).get(), userGamificationRef(uid).get(), ...USER_COLLECTIONS.map((collection) => db.collection(collection).where("userId", "==", uid).get())]); const data: Record<string, unknown> = { exportedAt: new Date().toISOString(), policyVersion: policy.version, profile: user.data() ?? null, gamification: gamification.exists ? gamification.data() : null }; USER_COLLECTIONS.forEach((collection, index) => { data[collection] = docs(snapshots[index] as FirebaseFirestore.QuerySnapshot); }); res.setHeader("Content-Disposition", `attachment; filename=meus-dados-rhythmos-${new Date().toISOString().slice(0, 10)}.json`); res.json(data); };
export const requestAccountDeletion = async (req: AuthenticatedRequest, res: Response) => { const uid = req.user!.uid; const now = new Date(); const scheduled = new Date(now.getTime() + 30 * 86400000); const reason = String(req.body?.reason ?? "").slice(0, 500); const [userDoc, existingRequest] = await Promise.all([db.collection("users").doc(uid).get(), db.collection("account_deletion_requests").doc(uid).get()]); if (existingRequest.data()?.status === "requested") return res.status(409).json({ message: "Já existe uma solicitação de exclusão em andamento." }); const user = userDoc.data() ?? {}; const supportRef = db.collection("supports").doc(`account-deletion-${uid}`); const requestRef = db.collection("account_deletion_requests").doc(uid); const createdAt = Timestamp.fromDate(now); const description = `Solicitação de exclusão de conta conforme LGPD.\n\nMotivo informado: ${reason || "Não informado"}\nExclusão prevista para: ${scheduled.toLocaleDateString("pt-BR")}.`; const support = { id: supportRef.id, userId: uid, userName: user.name ?? "Usuário", userEmail: user.email ?? "", title: "Solicitação de exclusão da conta", description, category: "conta", priority: "alta", status: "aberto", source: "account_deletion", deletionRequestId: uid, messages: [{ id: `deletion-${Date.now()}`, authorType: "usuario", authorId: uid, text: description, createdAt }], attachments: [], createdAt, updatedAt: createdAt, lastMessageAt: createdAt, closedAt: null }; const data = { userId: uid, userName: user.name ?? "Usuário", userEmail: user.email ?? "", supportId: supportRef.id, status: "requested", reason, requestedAt: createdAt, scheduledDeletionAt: Timestamp.fromDate(scheduled) }; const batch = db.batch(); batch.set(requestRef, data); batch.set(supportRef, support); await batch.commit(); return res.status(202).json({ message: "Solicitação registrada e encaminhada ao suporte.", supportId: supportRef.id, scheduledDeletionAt: scheduled.toISOString() }); };
export const cancelAccountDeletion = async (req: AuthenticatedRequest, res: Response) => { const uid = req.user!.uid; const requestRef = db.collection("account_deletion_requests").doc(uid); const request = await requestRef.get(); const supportId = request.data()?.supportId; const now = Timestamp.now(); const batch = db.batch(); batch.set(requestRef, { status: "cancelled", cancelledAt: now }, { merge: true }); if (supportId) batch.set(db.collection("supports").doc(supportId), { status: "fechado", closedAt: now, updatedAt: now }, { merge: true }); await batch.commit(); return res.json({ message: "Solicitação cancelada." }); };
export const revokeSessions = async (req: AuthenticatedRequest, res: Response) => { await auth.revokeRefreshTokens(req.user!.uid); const snapshot = await db.collection("user_sessions").where("userId", "==", req.user!.uid).get(); const batch = db.batch(); snapshot.docs.forEach((doc) => batch.set(doc.ref, { active: false, revokedAt: Timestamp.now() }, { merge: true })); await batch.commit(); res.json({ message: "Todas as outras sessões foram revogadas." }); };
