import { Router } from "express";
import { AnalyticsRoutes } from "./modules/analytics/analytics.routes";
import { BadgeRoutes } from "./modules/badges/badge.routes";
import { AssessmentsRoutes } from "./modules/assessments/assessment.routes";
import { CertificatesRoutes } from "./modules/certificates/certificate.routes";
import { ClinicalRoutes } from "./modules/clinical";
import { CrosswordRoutes } from "./modules/crosswords/crossword.routes";
import { EnrollmentsRoutes } from "./modules/enrollments/enrollment.routes";
import { GamesRouter } from "./modules/games/game.routes";
import { heatmapRouter } from "./modules/heatmap/heatmap.routes";
import { KnowledgeRoutes } from "./modules/knowledge/knowledge.routes";
import { ModulesRoutes } from "./modules/learning-modules/module.routes";
import { LessonsRoutes } from "./modules/lessons/lesson.routes";
import { LevelRoutes } from "./modules/levels/level.routes";
import { LaboratoryRoutes } from "./modules/laboratory/laboratory.routes";
import { PedagogicalAnalyticsRouter } from "./modules/pedagogical-analytics";
import { PollRoutes } from "./modules/polls/poll.routes";
import { RewardRoutes } from "./modules/rewards/reward.routes";
import { RhythmSketchRouter } from "./modules/rhythm-sketch";
import { RhythmRoutes } from "./modules/rhythms/rhythm.routes";
import { SketchbookRouter } from "./modules/sketchbook";
import { SupportRoutes } from "./modules/support/support.routes";
import { timelineRouter } from "./modules/timeline/timeline.routes";
import { TrailRoutes } from "./modules/trails/trail.routes";
import { UserProgressRoutes } from "./modules/users/user-progress.routes";
import { UserRoutes } from "./modules/users/user.routes";
import { AnnouncementRoutes } from "./modules/announcements/announcement.routes";
import { FeedbackRoutes } from "./modules/feedback/feedback.routes";
import { PrivacyRoutes } from "./modules/privacy/privacy.routes";
import { RecommendationRoutes } from "./modules/recommendations/recommendation.routes";
import { ClientErrorRoutes } from "./modules/observability/client-error.routes";
import { AppearanceRoutes } from "./modules/appearance/appearance.routes";
import { PasswordResetRoutes } from "./modules/auth/password-reset.routes";
import { RankingRoutes } from "./modules/gamification/ranking.routes";

export const userRoutes = Router();

userRoutes.use("/auth", PasswordResetRoutes);
userRoutes.use("/ranking", RankingRoutes);
userRoutes.use("/", UserRoutes);
userRoutes.use("/appearance", AppearanceRoutes);
userRoutes.use("/badges", BadgeRoutes);
userRoutes.use("/announcements", AnnouncementRoutes);
userRoutes.use("/feedback", FeedbackRoutes);
userRoutes.use("/privacy", PrivacyRoutes);
userRoutes.use("/recommendations", RecommendationRoutes);
userRoutes.use("/client-errors", ClientErrorRoutes);
userRoutes.use("/crosswords", CrosswordRoutes);
userRoutes.use("/rhythms", RhythmRoutes);
userRoutes.use("/analytics", AnalyticsRoutes);
userRoutes.use("/support", SupportRoutes);
userRoutes.use("/levels", LevelRoutes);
userRoutes.use("/laboratory-modules", LaboratoryRoutes);
userRoutes.use("/rewards", RewardRoutes);
userRoutes.use("/trails", TrailRoutes);
userRoutes.use("/games", GamesRouter);
userRoutes.use("/clinical-cases", ClinicalRoutes);
userRoutes.use("/heatmap", heatmapRouter);
userRoutes.use("/sketchbook", SketchbookRouter);
userRoutes.use("/rhythm-sketch", RhythmSketchRouter);
userRoutes.use("/knowledge", KnowledgeRoutes);
userRoutes.use("/modules", ModulesRoutes);
userRoutes.use("/lessons", LessonsRoutes);
userRoutes.use("/polls", PollRoutes);
userRoutes.use("/assessments", AssessmentsRoutes);
userRoutes.use("/certificates", CertificatesRoutes);
userRoutes.use("/progress", UserProgressRoutes);
userRoutes.use("/pedagogical-analytics", PedagogicalAnalyticsRouter);
userRoutes.use("/timeline", timelineRouter);
userRoutes.use("/enrollments", EnrollmentsRoutes);
